//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Data.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class LostAndFindEntities : DbContext
    {
        public LostAndFindEntities()
            : base("name=LostAndFindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mtblRole> mtblRoles { get; set; }
        public DbSet<tblUplodedFindPeople> tblUplodedFindPeoples { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
        public DbSet<tblQuesAn> tblQuesAns { get; set; }
    
        public virtual ObjectResult<Web_Roles_Result> Web_Roles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Web_Roles_Result>("Web_Roles");
        }
    
        public virtual ObjectResult<Web_SaveFindpeopleDetail_Result> Web_SaveFindpeopleDetail(Nullable<long> id, string firstName, string lastName, string findPeopleImage, Nullable<decimal> latitude, Nullable<decimal> longitude, string emailId, string phone, Nullable<bool> isActive, Nullable<bool> isApproved, string userId, string address, string fullAddress, string city, string state, string country, string pinCode, string lostOrFound)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var findPeopleImageParameter = findPeopleImage != null ?
                new ObjectParameter("FindPeopleImage", findPeopleImage) :
                new ObjectParameter("FindPeopleImage", typeof(string));
    
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(decimal));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("Longitude", longitude) :
                new ObjectParameter("Longitude", typeof(decimal));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var isApprovedParameter = isApproved.HasValue ?
                new ObjectParameter("IsApproved", isApproved) :
                new ObjectParameter("IsApproved", typeof(bool));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var fullAddressParameter = fullAddress != null ?
                new ObjectParameter("FullAddress", fullAddress) :
                new ObjectParameter("FullAddress", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var pinCodeParameter = pinCode != null ?
                new ObjectParameter("PinCode", pinCode) :
                new ObjectParameter("PinCode", typeof(string));
    
            var lostOrFoundParameter = lostOrFound != null ?
                new ObjectParameter("LostOrFound", lostOrFound) :
                new ObjectParameter("LostOrFound", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Web_SaveFindpeopleDetail_Result>("Web_SaveFindpeopleDetail", idParameter, firstNameParameter, lastNameParameter, findPeopleImageParameter, latitudeParameter, longitudeParameter, emailIdParameter, phoneParameter, isActiveParameter, isApprovedParameter, userIdParameter, addressParameter, fullAddressParameter, cityParameter, stateParameter, countryParameter, pinCodeParameter, lostOrFoundParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Web_SaveUsers(Nullable<long> id, string firstName, string lastName, string password, Nullable<long> roleId, string userName, string emailId, string phone, Nullable<long> userId, Nullable<bool> isActive)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(long));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Web_SaveUsers", idParameter, firstNameParameter, lastNameParameter, passwordParameter, roleIdParameter, userNameParameter, emailIdParameter, phoneParameter, userIdParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<Web_Users_Result> Web_Users(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Web_Users_Result>("Web_Users", idParameter);
        }
    
        public virtual ObjectResult<Web_GetFindpeopleDetail_Result> Web_GetFindpeopleDetail(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Web_GetFindpeopleDetail_Result>("Web_GetFindpeopleDetail", idParameter);
        }
    
        public virtual ObjectResult<VerifyLogin_Result> VerifyLogin(string emailId, string password)
        {
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerifyLogin_Result>("VerifyLogin", emailIdParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Web_GetAllQuestions_Result> Web_GetAllQuestions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Web_GetAllQuestions_Result>("Web_GetAllQuestions");
        }
    }
}
